import turtle

s = turtle.getscreen()
t = turtle.Turtle()
t.speed(5)

def square1():
    t.penup()
    t.goto(-250, 0)
    t.pendown()
    t.color("black", "brown")
    t.begin_fill()
    for i in range(3):
        t.fd(500)
        t.rt(90)
    t.fd(500)
    t.end_fill()
    t.penup()

def square2():
    t.penup()
    t.goto(-500, -500)
    t.pendown()
    t.color("black", "grey")
    t.begin_fill()
    for i in range(4):
        t.rt(90)
        t.fd(1000)
    t.end_fill()
    t.penup()

def square3():
    t.penup()
    t.goto(140, -400)
    t.pendown()
    t.color("black", "white")
    t.begin_fill()
    for i in range(4):
        t.rt(90)
        t.fd(100)
    t.end_fill()
    t.penup()

def square4():
    t.penup()
    t.goto(-200, -50)
    t.pendown()
    t.color("black", "lightblue")
    t.begin_fill()
    for i in range(4):
        t.rt(90)
        t.fd(120)
    t.end_fill()
    t.penup()

def right1():
    t.penup()
    t.goto(-250, 0)
    t.pendown()
    t.color("black", "black")
    t.begin_fill()
    t.fd(500)
    t.rt(135)
    t.fd(705)
    t.rt(135)
    t.fd(500)
    t.end_fill()
    t.penup()

def right2():
    t.penup()
    t.goto(-250, -500)
    t.pendown()
    t.color("black", "green")
    t.begin_fill()
    t.rt(90)
    t.fd(25)
    t.rt(135)
    t.fd(35.25)
    t.rt(135)
    t.fd(25)
    t.end_fill()
    t.penup()

def right3():
    t.penup()
    t.goto(-225, -500)
    t.pendown()
    t.color("black", "red")
    t.begin_fill()
    t.rt(90)
    t.fd(25)
    t.rt(135)
    t.fd(35.25)
    t.rt(135)
    t.fd(25)
    t.end_fill()
    t.penup()

def right4():
    t.penup()
    t.goto(-200, -500)
    t.pendown()
    t.color("black", "blue")
    t.begin_fill()
    t.rt(90)
    t.fd(25)
    t.rt(135)
    t.fd(35.25)
    t.rt(135)
    t.fd(25)
    t.end_fill()
    t.penup()

def cross1():
    t.penup()
    t.goto(220, -460)
    t.pendown()
    t.color("black", "grey")
    t.begin_fill()
    for i in range(4):
        t.fd(5)
        t.rt(90)
        t.fd(10)
        t.lt(90)
        t.fd(10)
        t.rt(90)
        t.fd(5)
    t.end_fill()
    t.penup()

def cross2():
    t.penup()
    t.goto(-140, -170)
    t.pendown()
    t.color("black", "yellow")
    t.begin_fill()
    for i in range(4):
        t.fd(5)
        t.rt(90)
        t.fd(55)
        t.lt(90)
        t.fd(55)
        t.rt(90)
        t.fd(5)
    t.end_fill()
    t.penup()

square1()
square2()
square3()
square4()
right1()
right2()
right3()
right4()
cross1()
cross2()